version: "3.3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    volumes:
      - ./db:/data/db
